### ISSUE TITLE
This repo seems interesting.

### ISSUE THREAD

**Issue by hemangjoshi37a** [xrsrke/instructGOOSE#1]
Please let me know if you want to develop anything in this direction. I want to contribute.

**Comment by xrsrke** [comment]
@hemangjoshi37a Hey. Here're some features that we'd love to support

<img width="466" alt="image" src="https://user-images.githubusercontent.com/22252984/221348654-b8d6c22c-ab83-4a0a-b28e-7588ba59bc26.png">

**Comment by hemangjoshi37a** [comment]
@xrsrke do you have any current developments in this directions?

**Comment by hemangjoshi37a** [comment]
@xrsrke  also what system are you using to train the models ?

**Comment by xrsrke** [comment]
Hey @hemangjoshi37a, apologies for the delayed response :). I do not have any plans for further development in this implementation, as I will be working on other papers. However, if you are interested in contributing, you are welcome to do so. I will review your commits.

**Comment by Bhood23** [comment]
Hey @xrsrke what hardware did you use to train instructGOOSE also can you give me and example of the output coming from instructGOOSE and what dataset do you recommend training with. Thank you I was just looking for a instructgpt local alternative and came across this!

**Comment by xrsrke** [comment]
1. I ran it on M1 Mac.
2. I'd recommend use https://huggingface.co/datasets/CarperAI/openai_summarize_comparisons 
3. What do you mean by "output coming from instructGOOSE"

**Comment by Bhood23** [comment]
> @Bhood23
> 
> 1. I ran it on M1 Mac.
> 2. I'd recommend use https://huggingface.co/datasets/CarperAI/openai_summarize_comparisons
> 3. What do you mean by "output coming from instructGOOSE"

Thanks, also I meant by output I meant the response from instructGOOSE

**Comment by Bhood23** [comment]
> @Bhood23 Sorry. Could you please elaborate like fro RewardModel, Agent, or RLHFTrainer? Because InstructGoose support you train your reward model, and train a huggingface model using RLHF

Oh sorry I was mistaken I didn't understand some stuff of AI I just researched and found out something. Sorry
