### ISSUE TITLE
forward() missing 1 required positional argument: 'attention_mask'

### ISSUE THREAD

**Issue by napawit44** [xrsrke/instructGOOSE#2]

**Comment by xrsrke** [comment]
hi. thanks. i will fix it!!

**Comment by xrsrke** [comment]
@napawit44 
hi. thanks. i will fix it!!

**Comment by xrsrke** [comment]
@napawit44 hey. the `forward()` of which class? you meant `RLHFTrainer.compute_loss()`?

**Comment by napawit44** [comment]
![image](https://user-images.githubusercontent.com/116282506/224615704-6cb13b18-2b01-4e07-8b2c-153d13d68e98.png)

Hi, It is this error from: rewards = reward_model(texts)

**Comment by napawit44** [comment]
I ran it on Colab

**Comment by xrsrke** [comment]
> I ran it on Colab

@napawit44  Alright, got it. I'll let you know after pushing the fix

**Comment by xrsrke** [comment]
@napawit44 hey. i just fixed the bug!!
